import { normalizeColor, validateOps, validateSpec, type BoardOp } from '../../shared/boardOps.js';
import { LessonBlueprintSchema, type LessonBlueprint } from '../../shared/pedagogy.js';
import { DeliveredTaskSchema, type DeliveredTask } from '../../shared/lessonTurn.js';
import { reduceLesson } from '../lesson/orchestrator.js';
import type { DomainRepository } from '../store/domain.js';
import type { CoordinatorContext } from './coordinatorContext.js';

/**
 * Session bootstrap after connect/reconnect: replay the board the child
 * actually saw, restore the durable blueprint and any unanswered task, and
 * hand a cold upstream model the story so far.
 */

type StoredEvents = Awaited<ReturnType<DomainRepository['listEvents']>>;

export async function replayBoard(ctx: CoordinatorContext): Promise<void> {
  // Only marks the child actually saw; ops cancelled mid-speech were
  // never released and must not reappear after a refresh. Stored ops are
  // re-validated so yesterday's data always meets today's rules.
  const events = await ctx.repo.listEvents(ctx.sessionId, 2000);
  const batches = events
    .filter((e) => ['board_ops', 'semantic_scene'].includes(e.type) && e.released)
    .map((e) => {
      const payload = e.payload as { ops?: unknown[]; semanticObjectId?: unknown; groupLabel?: unknown; replacesGroup?: unknown; plan?: { groups?: Array<{ id?: unknown; label?: unknown }> } };
      const ops = validateOps(payload.ops).ops;
      const semanticObjectId = typeof payload.semanticObjectId === 'string'
        ? payload.semanticObjectId
        : typeof payload.plan?.groups?.[0]?.id === 'string' ? payload.plan.groups[0].id : undefined;
      const groupLabel = typeof payload.groupLabel === 'string'
        ? payload.groupLabel
        : typeof payload.plan?.groups?.[0]?.label === 'string' ? payload.plan.groups[0].label : undefined;
      return {
        ops,
        ...(semanticObjectId ? { semanticObjectId } : {}),
        ...(groupLabel ? { groupLabel } : {}),
        ...(typeof payload.replacesGroup === 'string' && payload.replacesGroup ? { replacesGroup: payload.replacesGroup } : {}),
      };
    })
    .filter((batch) => batch.ops.length > 0);
  if (batches.length > 0) ctx.sendClient({ type: 'board_replay', batches });
  const learnerBatches = events
    .filter((event) => event.type === 'learner_board' && event.released)
    .map((event) => {
      const payload = event.payload as { ops?: unknown; semanticObjectId?: unknown };
      const ops = learnerBoardOps(payload.ops);
      return { ops, ...(typeof payload.semanticObjectId === 'string' ? { semanticObjectId: payload.semanticObjectId } : {}) };
    })
    .filter((batch) => batch.ops.length > 0);
  if (learnerBatches.length > 0) ctx.sendClient({ type: 'learner_board_replay', batches: learnerBatches });
  restoreBlueprint(ctx, events);
  await restoreDeliveredTask(ctx, events);
}

/** A refresh resumes the same blueprint at the same stage; the lesson plan
 * is durable and never regenerated by reconnecting. The compiled blueprint
 * is pre-seeded at connect; legacy sessions replay their stored
 * `lesson_blueprint` event. Either way, recorded progress reapplies. */
function restoreBlueprint(ctx: CoordinatorContext, events: StoredEvents): void {
  const preSeeded = ctx.state.lessonState.blueprint;
  let blueprint: LessonBlueprint | null = preSeeded;
  let progress: { currentStageIndex: number; detourStack: LessonBlueprint['detourStack'] } | null = null;
  for (const event of events) {
    if (event.type === 'lesson_blueprint' && !preSeeded) {
      const parsed = LessonBlueprintSchema.safeParse((event.payload as { blueprint?: unknown }).blueprint);
      if (parsed.success) { blueprint = parsed.data; progress = null; }
    } else if (event.type === 'blueprint_progress' && blueprint) {
      const payload = event.payload as { blueprintId?: unknown; currentStageIndex?: unknown; detourStack?: unknown };
      const matches = typeof payload.blueprintId !== 'string' || payload.blueprintId === blueprint.blueprintId;
      if (matches && typeof payload.currentStageIndex === 'number') {
        progress = {
          currentStageIndex: Math.max(0, Math.min(blueprint.stages.length - 1, payload.currentStageIndex)),
          detourStack: Array.isArray(payload.detourStack)
            ? (payload.detourStack as LessonBlueprint['detourStack']).slice(-4)
            : [],
        };
      }
    }
  }
  if (!blueprint) return;
  try {
    if (!preSeeded) {
      ctx.state.lessonState = reduceLesson(ctx.state.lessonState, { type: 'BLUEPRINT_CREATED', blueprint });
    }
    if (progress) {
      ctx.state.lessonState = {
        ...ctx.state.lessonState,
        blueprint: { ...blueprint, currentStageIndex: progress.currentStageIndex, detourStack: progress.detourStack },
      };
    }
  } catch { /* restoring an old blueprint never breaks the live lesson */ }
}

/** After a refresh, an unanswered task must survive: restore the contract
 * and show the banner again rather than losing the learner's turn. */
async function restoreDeliveredTask(ctx: CoordinatorContext, events: StoredEvents): Promise<void> {
  let openTask: DeliveredTask | null = null;
  for (const event of events) {
    if (event.type === 'learner_task') {
      const parsed = DeliveredTaskSchema.safeParse((event.payload as { task?: unknown }).task);
      if (parsed.success) openTask = parsed.data;
    } else if (['learner_said', 'learner_board'].includes(event.type)) openTask = null;
  }
  if (!openTask) return;
  try {
    ctx.state.lessonState = reduceLesson(ctx.state.lessonState, {
      type: 'QUESTION_DELIVERED', taskId: openTask.taskId, text: openTask.prompt, responseMode: openTask.responseMode,
    });
  } catch { /* restoring an old task never breaks the live lesson */ }
  ctx.sendClient({ type: 'learner_task', task: openTask, restored: true });
}

/** After a refresh the upstream model starts cold; hand it the story so far. */
export async function conversationContext(ctx: CoordinatorContext): Promise<string | null> {
  const events = await ctx.repo.listEvents(ctx.sessionId, 2000);
  const lines: string[] = [];
  for (const e of events) {
    const p = e.payload as { text?: string };
    if (e.type === 'tutor_said' && p.text) lines.push(`Tutor: ${p.text}`);
    if (e.type === 'learner_said' && p.text) lines.push(`Learner: ${p.text}`);
  }
  if (lines.length === 0) return null;
  return [
    'This lesson was interrupted by a page reload and is now resuming.',
    'What was said so far (oldest first):',
    ...lines.slice(-40),
    'The board still shows what was drawn. Resume naturally from where things left off — do not start over or repeat the greeting.',
  ].join('\n');
}

export function learnerBoardOps(raw: unknown): BoardOp[] {
  if (!Array.isArray(raw)) return [];
  const ops: BoardOp[] = [];
  for (const entry of raw.slice(0, 40)) {
    if (typeof entry !== 'object' || entry === null) continue;
    const candidate = entry as { op?: unknown; id?: unknown; color?: unknown; spec?: unknown };
    const id = typeof candidate.id === 'string' && /^sketch-[\w-]{1,80}$/.test(candidate.id)
      ? candidate.id
      : null;
    if (!id) continue;
    if (candidate.op === 'erase') {
      ops.push({ op: 'erase', id });
      continue;
    }
    if (candidate.op !== 'add' || typeof candidate.spec !== 'object' || candidate.spec === null) continue;
    const spec = validateSpec(candidate.spec as never);
    if (spec?.kind !== 'path') continue;
    const color = normalizeColor(candidate.color);
    ops.push({ op: 'add', id, spec, ...(color ? { color } : {}) });
  }
  return ops;
}

export function safeBoardImage(value: unknown): string | null {
  if (typeof value !== 'string' || value.length > 320_000) return null;
  return /^data:image\/(?:png|jpeg);base64,[a-z0-9+/=]+$/i.test(value) ? value : null;
}
